name: Deploy GitHub Pages (SUSPENDED)

on:
  workflow_dispatch:

jobs:
  suspended:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "IJR Pages deployment suspended on 2026-08-04 to prevent GitHub Actions usage."
